# Generated by Django 2.0.7 on 2018-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Desc', models.CharField(max_length=2000, null=True)),
                ('Opening_Time', models.CharField(default='Always open', max_length=30)),
                ('Entry_fee', models.CharField(default=0, max_length=8)),
                ('C_Name', models.CharField(max_length=300, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('Img_Path', models.CharField(max_length=300, null=True)),
                ('Popularity', models.CharField(max_length=10, null=True)),
                ('P_Name', models.CharField(max_length=50, null=True)),
                ('District', models.CharField(max_length=50, null=True)),
                ('Zone', models.CharField(max_length=50, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='place')),
                ('likes', models.PositiveIntegerField(default=13)),
                ('date_pub', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=2000, null=True)),
                ('Opening_Time', models.CharField(default='Always open', max_length=30)),
                ('Contact_No', models.CharField(max_length=20)),
                ('Popular_for', models.CharField(max_length=100)),
                ('C_Name', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('Img_Path', models.CharField(max_length=100)),
                ('P_Name', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=50)),
                ('Zone', models.CharField(max_length=50)),
                ('charge', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='restaurant')),
                ('likes', models.PositiveIntegerField(default=13)),
                ('date_pub', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
