# Generated by Django 2.0.7 on 2018-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0003_auto_20180814_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedetail',
            name='Desc',
            field=models.CharField(max_length=3500, null=True),
        ),
    ]
