# Generated by Django 2.0.5 on 2018-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=30)),
                ('viewer_id', models.IntegerField()),
                ('searched_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
