# Generated by Django 2.0.5 on 2018-08-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blogdislike_bloglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
