# Generated by Django 2.0.5 on 2018-07-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20180704_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog_Search',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
